# Generated by Django 3.2.3 on 2021-05-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=150)),
                ('Pai', models.CharField(max_length=100)),
                ('Mae', models.CharField(max_length=100)),
                ('CPF', models.IntegerField()),
                ('RG', models.IntegerField()),
                ('Nasc', models.IntegerField()),
                ('Endereco', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=150)),
                ('marca', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('valor', models.FloatField()),
                ('cilindradas', models.IntegerField()),
                ('cavalos', models.IntegerField()),
            ],
        ),
    ]
